export const vestGames = [
  { opponent: 'Campbell', outfit: 'Dark Gray Vest', result: 'W' },
  { opponent: 'NIU', outfit: 'Red Vest', result: 'W' },
  { opponent: 'Ball State', outfit: 'Black Vest', result: 'W' },
  { opponent: 'SIUE', outfit: 'Black with Bucky', result: 'W' },
  { opponent: 'BYU', outfit: 'Puffer with Block W', result: 'L' },
  { opponent: 'Providence', outfit: 'Red Vest', result: 'W' },
  { opponent: 'TCU', outfit: 'Black Pullover', result: 'L' },
  { opponent: 'Northwestern', outfit: 'Blue Suit', result: 'W' },
  { opponent: 'Marquette', outfit: 'Dark Gray Suit', result: 'W' },
  { opponent: 'Nebraska', outfit: 'Black with Old W', result: 'L' },
  { opponent: 'Villanova', outfit: 'Dark Gray Vest', result: 'L', overtime: true },
  { opponent: 'Central Michigan', outfit: 'Red Vest', result: 'W' },
  { opponent: 'Milwaukee', outfit: 'Light Gray Vest', result: 'W' },
  { opponent: 'Purdue', outfit: 'Blue Suit', result: 'L' },
  { opponent: 'UCLA', outfit: 'Red Vest', result: 'W' },
  { opponent: 'Michigan', outfit: 'Light Gray Vest', result: 'W' },
  { opponent: 'Minnesota', outfit: 'Red Vest', result: 'W' },
  { opponent: 'Rutgers', outfit: 'Light Gray Vest', result: 'W' },
  { opponent: 'Penn State', outfit: 'Red Vest', result: 'W' },
  { opponent: 'USC', outfit: 'Light Gray Vest', result: 'L' },
  { opponent: 'Minnesota', outfit: 'Red Vest', result: 'W' },
  { opponent: 'Ohio State', outfit: 'Blue Suit', result: 'W' },
];
